### ISSUE TITLE
internal validation - caclibration

### ISSUE THREAD

**Issue by MasaKusar** [danielegiardiello/Prediction_performance_survival#3]
Hello!

would it be possible to add the code for the internal validation for calibration.

Thank you!

**Comment by danielegiardiello** [comment]
Dear Masa,

thank you. 
I will notify you once I have extended the bootstrap_cv function available in [internal_cv.R](https://github.com/danielegiardiello/Prediction_performance_survival/blob/main/Functions/internal_cv.R) and potentially incorporated the internal validation assessment to the extended code  [03_predsurv_extended.md](https://github.com/danielegiardiello/Prediction_performance_survival/blob/main/03_predsurv_extended.md) and in the corresponding Rmarkdown source code [03_predsurv_extended.Rmd](https://github.com/danielegiardiello/Prediction_performance_survival/blob/main/03_predsurv_extended.Rmd).

Working in progress.

Best!
Daniele

**Comment by danielegiardiello** [comment]
Internal validation using optimism-corrected bootstrap was included in the function [internal_cv.R](https://github.com/danielegiardiello/Prediction_performance_survival/blob/main/Functions/internal_cv.R) and in the corresponding extended code [03_predsurv_extended.md](https://github.com/danielegiardiello/Prediction_performance_survival/blob/main/01_predsurv_minimal_RMD.md) and source code [03_predsurv_extended.Rmd](https://github.com/danielegiardiello/Prediction_performance_survival/blob/main/03_predsurv_extended.Rmd).

Best,
Daniele
